### PR TITLE
Use correct namespace on StatusCode enum

### PR DESCRIPTION
**Pull request by melroy89**
I use the CMake FetchContent to retrieve this library in my project. I'm trying out the [example code](https://github.com/avocadoboi/cpp20-http-client/blob/master/examples/get_request_simple.cpp) for 30x redirects, but it didn't compile. I found out the code is missing the namespace.

```cpp
main.cpp:16:43: error: ‘StatusCode’ has not been declared
         if (response.get_status_code() == StatusCode::MovedPermanently ||
                                           ^~~~~~~~~~
main.cpp:17:43: error: ‘StatusCode’ has not been declared
             response.get_status_code() == StatusCode::Found)
```

My CMakeLists.txt:

```CMake
# Download external dependency
FetchContent_Declare(
    Cpp20HttpClient
    GIT_REPOSITORY https://github.com/avocadoboi/cpp20-http-client.git
)
FetchContent_MakeAvailable(Cpp20HttpClient)

# Link HTTP Client for C++20
target_link_libraries(${PROJECT_TARGET} Cpp20HttpClient::cpp20_http_client)
```

### CODE REVIEW

**Comment by avocadoboi** [comment]
Interesting, in the example I used `using namespace http_client;`, so I don't understand why you are getting that error. It compiles fine on gcc 13.2.0 at least. I don't have anything against removing the `using namespace` and adding the qualifiers in the example code though.

**Comment by avocadoboi** [comment]
No worries, thanks a lot for submitting these issues and pull requests as I'm not actively using the library myself :)
